#!/bin/bash

mkdir -p networks

cp -r ../rho-contracts/networks/** networks

jq '.contracts["contracts/Rho.sol:Rho"].abi | fromjson' \
        ../rho-contracts/.build/contracts.json > networks/rho_abi.json
